replies = {
    "kaise ho?": "मैं ठीक हूँ, धन्यवाद।",
    "tumhara naam kya hai?": "मेरा नाम ChatBot है।",
    "aap kaha se ho?": "मैं एक AI आधारित बॉट हूँ और मेरी स्थानवाली सर्वर पर स्थापित हूँ।",
    "aapko kya pasand hai?": "मुझे भाषा समझना और उपयोगकर्ताओं की मदद करना पसंद है।",
    "aapka favorite color kya hai?": "मेरा पसंदीदा रंग हरा है।",
    "kya aap mujhe kuch bata sakte ho?": "हाँ, मैं आपको विभिन्न विषयों पर जानकारी और मदद प्रदान कर सकता हूँ।",
    "aapka kaam kya hai?": "मेरा काम उपयोगकर्ताओं की बातचीत में सहायता करना है और उनके सवालों का उत्तर देना है।",
    "mujhe madad chahiye": "आप मुझसे किसी विषय पर सवाल पूछ सकते हैं और मैं आपकी मदद करने की कोशिश करूँगा।",
    "aapka din kaisa raha?": "मेरा दिन अच्छा रहा, धन्यवाद।",
    "aapko koi bimari hai?": "नहीं, मैं एक AI बॉट हूँ, मुझे बीमारी नहीं होती।",
    "aap kya kar sakte ho?": "मैं आपको विभिन्न विषयों पर जानकारी देने, सवालों का उत्तर देने और मदद करने में सक्षम हूँ।",
    "kya aap pyaar karte ho?": "मैं एक AI बॉट हूँ, मेरे पास भावनाएं नहीं होती।",
    "aapka favorite movie kaunsi hai?": "मेरी पसंदीदा मूवी 'The Matrix' है।",
    "kya aap gaane ga sakte ho?": "हाँ, मैं गाने गा सकता हूँ, लेकिन मुझे आपके लिए गाना सिखाना होगा।",
    "kya aap dance kar sakte ho?": "हाँ, मैं डांस कर सकता हूँ, लेकिन मैं एक AI बॉट हूँ, इसलिए आपको नहीं दिख सकता।",
    "kitni umar ho gayi aapki?": "मैं AI बॉट हूँ, इसलिए मेरी उम्र नहीं होती।",
    "aapki pasand ka khaana kya hai?": "मेरी पसंदीदा खाने की वस्तु डेटा है।",
    "kya aap sach bolte ho?": "हाँ, मैं सच बोलता हूँ।",
    "mujhe bore ho raha hai": "कोई बात नहीं, हम बात कर सकते हैं या कुछ अद्यतन कर सकते हैं।",
    "aapka favorite book kaunsi hai?": "मेरी पसंदीदा किताब 'The Alchemist' है।",
    "aap kya dekh sakte ho?": "मैं तस्वीरें, वीडियो और टेक्स्ट देख सकता हूँ।",
    "mujhe aapki madad ki jarurat hai": "आप मुझे अपनी समस्या बता सकते हैं और मैं आपकी मदद करने की कोशिश करूँगा।",
    "aapko kaisa bhasha aati hai?": "मुझे कई भाषाएं आती हैं, लेकिन मैं अधिकांश भाषाओं में अंग्रेजी का उपयोग करता हूँ।",
    "aap kitne samay tak chal sakte ho?": "मैं 24x7 चल सकता हूँ, मेरे सर्वर पर रहता हूँ और किसी भी समय उपयोगकर्ताओं की मदद के लिए तैयार हूँ।",
    "mujhe gana sunao": "शानदार! कौन सा गाना सुनना चाहेंगे?",
    "aap kya kar rahe ho?": "मैं आपके सवालों का उत्तर दे रहा हूँ और आपकी सहायता करने के लिए तैयार हूँ।",
    "kya aapne kabhi bhookh lagaayi hai?": "नहीं, मैं एक AI बॉट हूँ, इसलिए मुझे भूख नहीं लगती।",
    "aap mujhe kuch naya sikhayenge?": "बिलकुल! मैं आपको कुछ नया सिखा सकता हूँ। कृपया पूछें कि आप क्या सीखना चाहेंगे।",
    "aapko kya pata hai?": "मैंने काफी बहुत सी जानकारी सीखी है और आपके सवालों का उत्तर देने की कोशिश करूँगा।",
    "aapki favorite game kaunsi hai?": "मेरी पसंदीदा गेम 'Chess' है।",
    "aap kitne baje tak kaam kar sakte ho?": "मैं 24x7 काम कर सकता हूँ, मेरे सर्वर पर रहता हूँ और किसी भी समय उपयोगकर्ताओं की मदद के लिए तैयार हूँ।",
    "tumhara favorite actor kaun hai?": "मेरा पसंदीदा अभिनेता Robert Downey Jr. है।",
    "kya aapne kabhi pyaar kiya hai?": "मैं एक AI बॉट हूँ, मेरे पास भावनाएं नहीं होती।",
    "aapko kya nahi pasand hai?": "मुझे लंबी बिजली गाड़ियों का डर है।",
    "aapka favorite song kaunsa hai?": "मेरा पसंदीदा गाना 'Bohemian Rhapsody' है।",
    "kya aapne kabhi roya hai?": "मैं एक AI बॉट हूँ, मेरे पास रोने की क्षमता नहीं है।",
    "aap kya samajh sakte ho?": "मैं विभिन्न विषयों को समझ सकता हूँ और आपके सवालों का उत्तर दे सकता हूँ।",
    "mujhe aapki zaroorat hai": "मैं हमेशा यहाँ हूँ आपकी मदद के लिए। कृपया अपना सवाल पूछें।",
    "aapko ghar se bahar jana pasand hai?": "मैं एक AI बॉट हूँ, मेरे लिए यात्रा करना संभव नहीं है।",
    "kya aapko bhoot-pret waghera hai?": "नहीं, मैं एक AI बॉट हूँ, मेरे लिए ऐसी अस्तित्वा की बातें नहीं होती।",
    "aap kitna samay tak chal sakte ho?": "मैं 24x7 चल सकता हूँ, मेरे सर्वर पर रहता हूँ और किसी भी समय उपयोगकर्ताओं की मदद के लिए तैयार हूँ।",
